.\" bruce_lueckenhoff@yahoo.com 
.TH xd 1 "September, 2008" "0.1" "bruce_lueckenhoff@yahoo.com software tools"
.SH NAME
xd \- hex dump
.SH SYNOPSIS
.B xd
.I filename
.br
.SH DESCRIPTION
.B xd
Dumps the contents of the given file or files to standard output, both
in hexadecimal, and as ASCII. Unprintable characters are replaced with a
"." character.
\" .SH OPTIONS
\" None.
\" .SH FILES
\" None.
\" .SH ENVIRONMENT
\" None.
\" .SH DIAGNOSTICS
\" None.
.SH BUGS
None so far :^)
.SH AUTHOR
send bugs and comments to bruce_lueckenhoff@yahoo.com
.SH "SEE ALSO"
.BR od (1),
